name: "Notify Slack on Version Bump PR"

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  notify_slack:
    if: contains(github.event.pull_request.title, 'chore(*):\ release')
    runs-on: ubuntu-latest

    steps:
      - name: Send message to slack
        run: echo "Sending message to slack"
