name: Lock Branch

on:
  push:
    branches:
      - master

jobs:
  lock-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Lock Branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.MERGE_FREEZE_ALL_PERM }}
          script: |
            const branch = 'master';
            
            const response = await github.rest.repos.getBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch,
            });
            console.log('GET BRANCH PROTECTION', JSON.stringify(response, null, 2));
            const { data } = response;
            
            let restrictions = null;
            try {
              const response = await github.rest.repos.getAccessRestrictions({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch,
              });
            
              console.log('GET GET ACCESS RESTRICTIONS', JSON.stringify(response, null, 2));
            
              if (response.status === 200) {
                const { data } = response;
                const { users, teams, apps } = { data };
                restrictions = { users, teams, apps };
              }
              console.error(
                `Couldn't get access restrictions for ${branch} branch.`,
                JSON.stringify(response, null, 2)
              );
            } catch (e) {
              console.error(
                `Couldn't get access restrictions for ${branch} branch.`,
                JSON.stringify(e, null, 2)
              );
            }
            
            const { url, ...required_pull_request_reviews } = response.data.required_pull_request_reviews;
            const enforce_admins = response.data.enforce_admins.enabled;
            const { url: url1, contexts_url, ...required_status_checks } = response.data.required_status_checks;
            
            try {
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch,
                required_status_checks: null, // TODO: fixme
                enforce_admins,
                required_pull_request_reviews,
                restrictions,
                lock_branch: true,
              });
              console.log(`Branch ${branch} has been locked.`);
            } catch (e) {
              console.error(
                `Couldn't update branch protection for ${branch} branch.`,
                JSON.stringify(e, null, 2)
              );
            }


            

