name: Lock Branch

on:
  push:
    branches:
      - master

jobs:
  lock-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Lock Branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.MERGE_FREEZE_ALL_PERM }}
          script: |
            const branch = 'master';
            
            const response = await github.rest.repos.getBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch,
            });
            console.log('GET BRANCH PROTECTION', JSON.stringify(response,null, 2) );
            const { data } = response;
            const { required_status_checks, enforce_admins, required_pull_request_reviews } = data;
            
            let restrictions = null;
            try {
              const response = await github.rest.repos.getAccessRestrictions({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch,
              });

              console.log('GET GET ACCESS RESTRICTIONS', JSON.stringify(response,null, 2) );
            
              if (response.status === 200) {
                const { data } = response;
                const { users, teams, apps } = { data };
                restrictions = { users, teams, apps };
              }
              console.error(
                `Couldn't get access restrictions for ${branch} branch.`,
                JSON.stringify(response, null, 2)
              );
            } catch (e) {
              console.error(
                `Couldn't get access restrictions for ${branch} branch.`,
                JSON.stringify(response, null, 2)
              );
            }
            /*
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch,
              required_status_checks,
              enforce_admins,
              lock_branch: true,
              restrictions,
              required_pull_request_reviews,
            });
            console.log(`Branch ${branch} has been locked.`);
            */

