name: Lock Branch

on:
  workflow_dispatch:
    inputs:
      parameter:
        description: My Parameter
  pull_request:
    types: [ labeled ]

env:
  MERGE_FREEZE_ISSUE_NUMBER: 6
  PR_URL: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}

jobs:
  lock-branch:
    runs-on: ubuntu-latest
    steps:
      - name: 👀 Checking if the merge freeze issue is closed
        id: get-merge-freeze-issue-data
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/issues/{issue_number}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ env.MERGE_FREEZE_ISSUE_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail if merge freeze issue is open
        if: fromJson(steps.get-merge-freeze-issue-data.outputs.data).state == 'open'
        run: exit 1

      - name: 🔒 Enabling the merge freeze
        uses: marocchino/sticky-pull-request-comment@v2
        if: always() && fromJson(steps.get-merge-freeze-issue-data.outputs.data).state == 'open'
        with:
          header: merge-freeze-error
          message: |
             🛑 Merge freeze is now enabled.
      - if: fromJson(steps.get-merge-freeze-issue-data.outputs.data).state == 'closed'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: merge-freeze-error
          delete: true